/**
 * Prints the calibration record as Markdown: for every car and engine variant,
 * the factory figures under their own rating standard, the model at those
 * same conditions and at the site's defaults (45 °C in Riyadh on PG95); then
 * every known build (BUILD_PROMPT 6.5), its sheet against the model.
 *
 *   npx tsx scripts/calibration-report.ts > docs/calibration.md
 *
 * The pass/fail gates themselves are tests/calibration/stock.test.ts and
 * tests/calibration/known-builds.test.ts; this is the human-readable record.
 */
import { buildCatalogue } from '../src/data/loader';
import { TO_SI } from '../src/data/units';
import { KNOWN_BUILD_TOLERANCE, simulateKnownBuild } from '../src/sim/known-builds';
import { FitCache, defaultConditions, pressureFor, simulateTrim } from '../src/sim/simulate';
import { readRawData } from './vite-plugin-catalogue';

const catalogue = buildCatalogue(readRawData(process.cwd()).raw);
const cache = new FitCache();
const DEFAULT_CONDITIONS = defaultConditions(catalogue);
const defaultPressure = (pressureFor(DEFAULT_CONDITIONS, catalogue) / 1000).toFixed(1);

const STANDARD: Record<string, string> = {
  'JIS-net': 'JIS',
  'SAE-net': 'SAE',
  'DIN-70020': 'DIN',
  'EEC-80/1269': 'ECE',
};

/** "250 PS" -> the unit and a formatter for SI values in that unit. */
function inPrinted(printed: string): (si: number) => string {
  const unit = printed.slice(printed.indexOf(' ') + 1);
  const factor = (TO_SI as Record<string, number>)[unit];
  if (factor === undefined) throw new Error(`Unknown unit in "${printed}"`);
  const digits = unit === 'kgf·m' ? 1 : 0;
  return (si) => `${(si / factor).toFixed(digits)} ${unit}`;
}

const pct = (x: number) => `${x >= 0 ? '+' : '−'}${Math.abs(x * 100).toFixed(1)} %`;
const rpm = (n: number) => n.toLocaleString('en-US');

const lines: string[] = [];
let trims = 0;
let passed = 0;
lines.push('# Calibration record');
lines.push('');
lines.push(
  `Generated by \`npx tsx scripts/calibration-report.ts\`. Each row is one engine variant as fitted to a car; the trims that share it have the same engine figures (gearboxes only change the wheel-power estimate). "Factory" is the published figure, compared at its own rating standard (reference air and the market’s rating fuel); "Model" is the simulation at those same conditions; the last column is the model at the site defaults, 45 °C ambient in Riyadh (${defaultPressure} kPa) on PG95 (95 RON). The pass mark is 3 % on each peak and 250 rpm on each peak’s rpm.`,
);
lines.push('');

for (const car of catalogue.cars) {
  const groups = new Map<string, typeof car.trims>();
  for (const trim of car.trims) {
    const key = `${trim.engine.id}/${trim.engine.variant}`;
    groups.set(key, [...(groups.get(key) ?? []), trim]);
  }
  lines.push(`## ${car.make} ${car.model} (${car.chassis})`);
  lines.push('');
  lines.push(
    '| Engine variant | Trims | Standard | Factory power | Model | Factory torque | Model | At 45 °C in Riyadh, PG95 |',
  );
  lines.push('|---|---:|---|---|---|---|---|---|');
  for (const group of groups.values()) {
    const results = group.map((t) =>
      simulateTrim(catalogue, car.id, t.id, DEFAULT_CONDITIONS, cache),
    );
    trims += results.length;
    passed += results.filter((r) => r.calibration.pass).length;
    const sim = results[0];
    if (!sim) continue;
    const c = sim.calibration;
    const printed = sim.variant.rating.printed;
    const p = inPrinted(printed.power);
    const t = inPrinted(printed.torque);
    const standard = `${STANDARD[sim.rating.standard.id] ?? sim.rating.standard.id}${
      sim.rating.assumed ? ' (assumed)' : ''
    }`;
    const allPass = results.every((r) => r.calibration.pass);
    const hot = sim.run;
    lines.push(
      [
        '',
        `${sim.variant.name}${allPass ? '' : ' **FAILS**'}`,
        String(group.length),
        standard,
        `${p(c.power.factory)} at ${rpm(c.power.factoryRpm)}`,
        `${p(c.power.model)} at ${rpm(c.power.modelRpm)} (${pct(c.power.error)})`,
        `${t(c.torque.factory)} at ${rpm(c.torque.factoryRpm)}`,
        `${t(c.torque.model)} at ${rpm(c.torque.modelRpm)} (${pct(c.torque.error)})${
          c.curve
            ? `; curve max ${Math.max(...c.curve.map((x) => Math.abs(x.error * 100))).toFixed(1)} % over ${String(c.curve.length)} points`
            : ''
        }`,
        `${p(hot.peakPower.value)} (${pct(hot.peakPower.value / c.power.factory - 1)}), ${t(hot.peakTorque.value)} (${pct(
          hot.peakTorque.value / c.torque.factory - 1,
        )})`,
        '',
      ]
        .join(' | ')
        .trim(),
    );
  }
  lines.push('');
}

lines.splice(
  2,
  0,
  '## Stock calibration',
  '',
  `**${String(passed)} of ${String(trims)} trims pass.**`,
  '',
);

const hp = (w: number) => `${(w / 745.7).toFixed(1)} hp`;
const builds = catalogue.knownBuilds.map((b) => ({
  b,
  r: simulateKnownBuild(catalogue, b, cache),
}));
lines.push('## Known builds');
lines.push('');
const counted = builds.filter((x) => !x.b.excluded);
lines.push(
  `Documented real builds with a published sheet (src/data/builds/), run with their parts, boost, fuel and dyno-day air and turned into what their own dyno would print (reading against a Dynojet, and the sheet's correction standard). Pass mark: within ${String(KNOWN_BUILD_TOLERANCE * 100)} % of the sheet's peak wheel power. **${String(counted.filter((x) => x.r.pass).length)} of ${String(counted.length)} pass.**${counted.length < builds.length ? ` ${String(builds.length - counted.length)} more ${builds.length - counted.length === 1 ? 'is' : 'are'} listed but not counted (marked, with the reason).` : ''}`,
);
lines.push('');
lines.push('| Car | Build | Dyno, correction | Sheet | Model | Off by |');
lines.push('|---|---|---|---:|---:|---:|');
for (const { b, r } of builds) {
  const car = catalogue.cars.find((c) => c.id === b.carId);
  const dyno = catalogue.dynos.find((d) => d.id === b.result.dyno)?.name ?? b.result.dyno;
  const correction =
    catalogue.corrections.find((c) => c.id === b.result.correction)?.name ?? b.result.correction;
  lines.push(
    [
      '',
      car ? `${car.model} (${car.chassis})` : b.carId,
      `[${b.title}](${b.source.url})`,
      `${dyno}, ${correction}${b.result.correctionAssumed ? ' (assumed)' : ''}`,
      hp(r.measured),
      hp(r.predicted),
      b.excluded
        ? `${pct(r.error)} (not counted: ${b.excluded.reason})`
        : `${pct(r.error)}${r.pass ? '' : ' **FAILS**'}`,
      '',
    ]
      .join(' | ')
      .trim(),
  );
}
lines.push('');
process.stdout.write(`${lines.join('\n')}\n`);
