/**
 * Prints the stock calibration table as Markdown: for every car and engine
 * variant, the factory figures under their own rating standard, the model at
 * those same conditions, and the model at the site's defaults (45 °C, 95 RON).
 *
 *   npx tsx scripts/calibration-report.ts > docs/calibration.md
 *
 * The pass/fail gate itself is tests/calibration/stock.test.ts; this is the
 * human-readable record of it.
 */
import { buildCatalogue } from '../src/data/loader';
import { TO_SI } from '../src/data/units';
import { DEFAULT_CONDITIONS, FitCache, simulateTrim } from '../src/sim/simulate';
import { readRawData } from './vite-plugin-catalogue';

const catalogue = buildCatalogue(readRawData(process.cwd()).raw);
const cache = new FitCache();

const STANDARD: Record<string, string> = {
  'JIS-net': 'JIS',
  'SAE-net': 'SAE',
  'DIN-70020': 'DIN',
  'EEC-80/1269': 'ECE',
};

/** "250 PS" -> the unit and a formatter for SI values in that unit. */
function inPrinted(printed: string): (si: number) => string {
  const unit = printed.slice(printed.indexOf(' ') + 1);
  const factor = (TO_SI as Record<string, number>)[unit];
  if (factor === undefined) throw new Error(`Unknown unit in "${printed}"`);
  const digits = unit === 'kgf·m' ? 1 : 0;
  return (si) => `${(si / factor).toFixed(digits)} ${unit}`;
}

const pct = (x: number) => `${x >= 0 ? '+' : '−'}${Math.abs(x * 100).toFixed(1)} %`;
const rpm = (n: number) => n.toLocaleString('en-US');

const lines: string[] = [];
let trims = 0;
let passed = 0;
lines.push('# Stock calibration (Phase 2a)');
lines.push('');
lines.push(
  'Generated by `npx tsx scripts/calibration-report.ts`. Each row is one engine variant as fitted to a car; the trims that share it have the same engine figures (gearboxes only change the wheel-power estimate). "Factory" is the published figure, compared at its own rating standard (reference air and the market’s rating fuel); "Model" is the simulation at those same conditions; the last columns are the model at the site defaults, 45 °C ambient, 101.3 kPa and 95 RON. The pass mark is 3 % on each peak and 250 rpm on each peak’s rpm.',
);
lines.push('');

for (const car of catalogue.cars) {
  const groups = new Map<string, typeof car.trims>();
  for (const trim of car.trims) {
    const key = `${trim.engine.id}/${trim.engine.variant}`;
    groups.set(key, [...(groups.get(key) ?? []), trim]);
  }
  lines.push(`## ${car.make} ${car.model} (${car.chassis})`);
  lines.push('');
  lines.push(
    '| Engine variant | Trims | Standard | Factory power | Model | Factory torque | Model | At 45 °C, 95 RON |',
  );
  lines.push('|---|---:|---|---|---|---|---|---|');
  for (const group of groups.values()) {
    const results = group.map((t) =>
      simulateTrim(catalogue, car.id, t.id, DEFAULT_CONDITIONS, cache),
    );
    trims += results.length;
    passed += results.filter((r) => r.calibration.pass).length;
    const sim = results[0];
    if (!sim) continue;
    const c = sim.calibration;
    const printed = sim.variant.rating.printed;
    const p = inPrinted(printed.power);
    const t = inPrinted(printed.torque);
    const standard = `${STANDARD[sim.rating.standard.id] ?? sim.rating.standard.id}${
      sim.rating.assumed ? ' (assumed)' : ''
    }`;
    const allPass = results.every((r) => r.calibration.pass);
    const hot = sim.run;
    lines.push(
      [
        '',
        `${sim.variant.name}${allPass ? '' : ' **FAILS**'}`,
        String(group.length),
        standard,
        `${p(c.power.factory)} at ${rpm(c.power.factoryRpm)}`,
        `${p(c.power.model)} at ${rpm(c.power.modelRpm)} (${pct(c.power.error)})`,
        `${t(c.torque.factory)} at ${rpm(c.torque.factoryRpm)}`,
        `${t(c.torque.model)} at ${rpm(c.torque.modelRpm)} (${pct(c.torque.error)})${
          c.curve
            ? `; curve max ${Math.max(...c.curve.map((x) => Math.abs(x.error * 100))).toFixed(1)} % over ${String(c.curve.length)} points`
            : ''
        }`,
        `${p(hot.peakPower.value)} (${pct(hot.peakPower.value / c.power.factory - 1)}), ${t(hot.peakTorque.value)} (${pct(
          hot.peakTorque.value / c.torque.factory - 1,
        )})`,
        '',
      ]
        .join(' | ')
        .trim(),
    );
  }
  lines.push('');
}

lines.splice(4, 0, `**${String(passed)} of ${String(trims)} trims pass.**`, '');
process.stdout.write(`${lines.join('\n')}\n`);
